platform :ios, '11.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

target 'InSessionSample' do

  config = use_native_modules!
  use_frameworks!
  
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end

  target 'InSessionSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'InSessionSample-tvOS' do
  # Pods for InSessionSample-tvOS

  target 'InSessionSample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
